#! /bin/bash

cd "$APPDIR"

if [ -d /usr/lib/$(uname -m)-linux-gnu/qt5 ] || [ -d /usr/lib/qt ]; then
    # System-wide Qt5
    exec ./citron.sh "$@"
else
    # Bundled Qt5
    exec ./citron-bqt.sh "$@"
fi
